/** Known test foods for deterministic assertions */
export const TEST_FOODS = {
  blackBeans: {
    name: 'black_beans_cooked',
    name_display: 'Black Beans (cooked)',
    glycemic_index: 30,
    glycemic_load: 5,
    traffic_light: 'green' as const,
    barcode: '0000000000001',
    confidence_score: 0.95,
    data_source: 'published_study',
    swap_tip: null,
    carbs_g: 23,
    fiber_g: 8,
    available_carbs_g: 15,
  },
  flourTortilla: {
    name: 'flour_tortilla',
    name_display: 'Flour Tortilla',
    glycemic_index: 53,
    glycemic_load: 15,
    traffic_light: 'yellow' as const,
    barcode: '0000000000002',
    confidence_score: 0.9,
    data_source: 'published_study',
    swap_tip: 'Try corn tortilla with beans for lower impact',
  },
  cornTortilla: {
    name: 'corn_tortilla_white',
    name_display: 'Corn Tortilla (white)',
    glycemic_index: 74,
    glycemic_load: 22,
    traffic_light: 'red' as const,
    barcode: '0000000000003',
    confidence_score: 0.9,
    data_source: 'published_study',
    swap_tip: 'Add beans or nopal to lower glucose impact',
  },
  boundaryYellow: {
    name: 'boundary_yellow_food',
    name_display: 'Boundary Yellow Food',
    glycemic_index: 50,
    glycemic_load: 10,
    traffic_light: 'yellow' as const,
    barcode: '0000000000004',
    confidence_score: 0.8,
    data_source: 'expert_estimated',
  },
  boundaryRed: {
    name: 'boundary_red_food',
    name_display: 'Boundary Red Food',
    glycemic_index: 65,
    glycemic_load: 20,
    traffic_light: 'red' as const,
    barcode: '0000000000005',
    confidence_score: 0.8,
    data_source: 'expert_estimated',
  },
  thresholdSensitiveFood: {
    name: 'threshold_sensitive_food',
    name_display: 'Threshold Sensitive Food',
    glycemic_index: 55,
    glycemic_load: 14,
    traffic_light: 'yellow' as const,
    barcode: '0000000000006',
    confidence_score: 0.7,
    data_source: 'expert_estimated',
  },
}

export const TEST_OXXO_PRODUCTS = {
  cocaColaOriginal: {
    product_name: 'Coca-Cola Original (600ml)',
    brand: 'Coca-Cola',
    barcode: '7501055300112',
    category: 'drinks_sugary',
    estimated_gi: 80,
    estimated_gl: 33,
    traffic_light: 'red' as const,
    swap_suggestion: 'Swap for: Coca-Cola Zero or Ciel Mineralizada',
    why_tip: '63g of pure sugar. One of the highest glucose spikes you can drink.',
    store_chain: 'oxxo',
  },
  cielMineralizada: {
    product_name: 'Ciel Mineralizada',
    brand: 'Ciel',
    barcode: '7501055300229',
    category: 'drinks_water',
    estimated_gi: 0,
    estimated_gl: 0,
    traffic_light: 'green' as const,
    swap_suggestion: null,
    why_tip: 'Zero carbs, zero glucose impact. Always the safest choice.',
    is_best_choice: true,
    store_chain: 'oxxo',
  },
  cacahuatesJaponeses: {
    product_name: 'De La Rosa Cacahuates Japoneses',
    brand: 'De La Rosa',
    barcode: '7501027200112',
    category: 'snacks_nuts_seeds',
    estimated_gi: 25,
    estimated_gl: 4,
    traffic_light: 'green' as const,
    is_best_choice: true,
    store_chain: 'oxxo',
  },
}

export const ONBOARDING_PROFILES = {
  healthy: {
    healthState: 'healthy',
    goal: 'learn',
    age: 35,
    sex: 'female',
    activityLevel: 'moderate',
    dietaryRestrictions: [],
    medications: [],
    mealStruggles: [],
  },
  type2: {
    healthState: 'type2',
    goal: 'lower_a1c',
    a1cValue: 7.8,
    age: 55,
    sex: 'male',
    activityLevel: 'sedentary',
    medications: ['Metformin'],
    dietaryRestrictions: [],
    mealStruggles: [],
  },
  prediabetic: {
    healthState: 'prediabetic',
    goal: 'lose_weight',
    age: 45,
    sex: 'female',
    activityLevel: 'light',
    dietaryRestrictions: ['Vegetarian'],
    medications: [],
    mealStruggles: [],
  },
}
